### ISSUE TITLE
Congratulations and Requests

### ISSUE THREAD

**Issue by technician77** [m-parashar/emax64#1]
First I would like to express my gratitude for your release, especially for epdfinfo and Image Magick 7. Epdfinfo gave me a major headache. For some reason I was not able to compile a functional version under cygwin dispite trying many times. For other reasons I couldn't switch to (supported) MSYS2.

Then I have a request. Could you integrate fakecygpty? It's the only program that I need to complile under cygwin. It enables using a working (cygwin) bash in ntemacs. Details:
[https://www.emacswiki.org/emacs/NTEmacsWithCygwin](https://www.emacswiki.org/emacs/NTEmacsWithCygwin)
Download:
[https://github.com/d5884/fakecygpty/](https://github.com/d5884/fakecygpty/)

Have you checked the official repository? I have to doublecheck but it seems
[https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-26-snapshot-x86_64.zip](https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-26-snapshot-x86_64.zip)
does contain a lot more files in /bin. On the other hand I couldn't find missing functionality - YET.
Please evaluate if your distribution is identical (in terms of "distribution"-scope) to this version.
If not please advise if possible.

One more question: You fully integrated Image Magick 7, batteries included so to speak. Would it be technical possible to compile with IM7 support but not to include it? The reasoning behind is that many integrated software gets less or at least delayed updated. Especially in security context this could be a disadvantage. In cases where not even binaries exist (like epdfinfo) including makes a lot sense. But IM7 has not only binaries it has also an installer. I these regards it's similar to ghostscript.
[https://www.imagemagick.org/script/download.php#windows](https://www.imagemagick.org/script/download.php#windows)

**Comment by m-parashar** [comment]
Thank you, technician77. I appreciate the feedback and I'm glad you find it useful.

I have looked into fakecygpty, it is almost impossible to compile it with MSYS2or even statically within Cygwin, hence I'll have to bundle Cygwin runtime as well. I'll look into it, especially the redistribution clauses in the license. For now I am uploading the binaries.

The official deps (or the latest snapshot bundle) include a lot of MSYS2 stuff that unnecessarily bloats the distribution as these can be easily obtained from the MSYS/MinGW repositories. Despite the bloat, it doesn't include a lot of useful stuff either. For now, I intend to keep this distribution lean and complete, as in dependencies are bundled but not the whole POSIX system just for an editor. I have a better package in the works which uses BusyBox and GNU utilities in a tandem to provide a sane environment for Emacs on Windows.

Which brings us to the IM7 issue. Yes, I'd have preferred to just fix the missing support for IM7 instead of the batteries included approach. Unfortunately, the official IM7 Windows binaries do not play well with the MSYS2/MinGW64 toolchain. I will give it another try within the next few days and stop including IM7 binaries and runtime if everything goes well. For now, emax64 is lean and sane enough considering the alternatives.

Thank you for your time and suggestions. Keep 'em flowing.

**Comment by technician77** [comment]
Thanks for your comprehensive answer. Some remarks:

Bundling cygwin is not a good idea since you would need to keep up with their updates to be in sync. Maybe the author of fakecygpty can find a solution. If it's o.k. I would open an issue there so he can comment on that.

Well, on my work pc I have to use cygwin, but because of the Anti-Virus app it is slow as hell. If I'm correct the bin bloat works without cygwin aka native and is seemingly faster in execution. Therefore I would like to have as much bundled as possible, but I presume I'm an edge case. The busy-box idea sounds interesting. I hope the AV likes it more than it does cygwin.

Kind regards,
tech77

**Comment by m-parashar** [comment]
You are most welcome.

Bundling Cygwin is not on my todo list since I avoid it as much as I can. WSL is growing up fast into a mature alternative.

The Emacs dependency package includes a lot of unnecessary stuff, and I am of the opinion that any person interested in using Emacs on Windows along with the GNU toolchain would prefer to install either MSYS/MinGW or Git for Windows packages, and both provide a much better environment for Emacs. I will soon release a minimal, yet functional, sane environment package for Emacs on Windows.

For now, you can add the root folder to your antivirus exclusion list. Windows Defender is a menace.

Best.

**Comment by technician77** [comment]
You assume I have control over the Anti-Virus, which I don't have and it's not Windows Defender. I managed to migrate to MSYS2 for now, but I'm not sure if I can stay on that.

From what I heard the WSL on Win 10 is a full Ubuntu, but I still (have to) use a Win 7 machine. I might consider testing the WSL if I can ditch the Win7 machine, but then again installation might be unavailable on that machine.

I recently tried the emojify package. From what I read it displays png images by default and uses imagemagick to show them properly. The package downloads the pngs on the first run. For some reason if I try an emoji like :-) it looks this 
![image](https://user-images.githubusercontent.com/18722291/34367266-a0020e00-eaa8-11e7-821d-21ea03f8005c.png)
Can you reproduce (if you got the time)?

Kind regards,
tech77

**Comment by technician77** [comment]
For reasons unknow the emoji problem disappeard. They are now shown correctly when image mode is used, so please ignore this in post above.

**Comment by ordicker** [comment]
Hi, 

Just a quick question that seem related to the post. 

How do you use ssh without fakecygpty? 
I am trying to setup remote python REPL using tramp(windows->linux remote machine).
But I cant make it work :(

Thank you.
