### ISSUE TITLE
How to use PDF-Tools? (for dummies)

### ISSUE THREAD

**Issue by Ypot** [m-parashar/emax64#14]
Hi

I am starting to use emacs and org-mode, so not much literate.
When I try to open a PDF it uses Doc view.
I am running the Windows 64 package, but not using MSYS2. Just unziped out of the box, it works great and without problems.
 What must be done to use PDF- tools? Is it possible to do it without using MSYS2?

Thanks for your work!

**Comment by novoid** [comment]
I, too, had issues understanding the procedure. I don't have MSYS2 but I am using babun which is a Cygwin-distribution. When I looked into the dependencies, the list was enormously long and resulted in complicated compiling that did not work out here. (Sorry, no details because it was some time ago - if it is important, I could re-try and post the issues.)

I just gave up and do not use PDF-Tools which would be a nice-to-have to me.

**Comment by Ypot** [comment]
I asked because the Readme says that PDF-TOOLS is included, and I thought it would work out of the box.

Let's wait it gets better. 

Thanks!

**Comment by m-parashar** [comment]
PDF-TOOLS is included, but to ensure proper and smooth operation you need to download the package emax.7z and extract it in your HOME directory, as mentioned in the README. This is required as pdf-tools is set up as a melpa package - compiled and ready for use with a couple of bug fixes as well. You could just copy the pdf-tools directory from the above mentioned package to your own setup and use it.

**Comment by novoid** [comment]
On Debian stable I had to install `elpa-pdf-tools-server` (which is not available on my (X)Ubuntu 14.04 LTS). On Windows 10, I did not want to extract Emacs outside of `C:\Program files\` and therefore I extended my `PATH` environment variable to the `bin` folder of emacs, rebooted and then pdf-tools worked.
