### ISSUE TITLE
No images/icons in mode line

### ISSUE THREAD

**Issue by novoid** [m-parashar/emax64#23]
After upgrading from the 25.x to 26.2 (latest Windows 10), I noticed that all graphics I tend to have in my mode line are back to text only:
https://github.com/ryuslash/mode-icons and also https://github.com/TeMPOraL/nyan-mode

Maybe somebody can confirm this effect.

Let me know when I should check something.

**Comment by etern** [comment]
I can confirm this, something wrong with icons.
Not only `nyan mode`, `tool-bar-mode` icons seems like pure text. 
If I try to open `neotree` which uses `all-the-icons` , emacs will freeze, from task manager, I can see it consumes a lot of cpu and memory.

**Comment by bcully** [comment]
same here

**Comment by xeijin** [comment]
@novoid  @etern  @bcully I wonder if this is because the latest version is built with Imagemagick **7** rather than version 6?

I believe version 7 is currently incompatible with emacs in general, Windows aside, if it's being used to render icons / graphics that may explain why these are not showing

**Comment by novoid** [comment]
I'm sorry: I don't have access to the Windows 10 machine that had the issue any longer.

@etern or @bcully: Are you willing to take over? (Or should I close the issue?)

**Comment by m-parashar** [comment]
I will attempt another patched build by this weekend.

@xeijin The whole point of these releases is to build against IM7 and the last few releases have worked as expected. Changes to the last official release may have introduced incompatibility with IM7 patch, hence the issues.

PS: My work leaves little time these days to tinker with software and patch broken support. If I cannot continue to provide production quality builds and support, I would prefer if someone else took over and continued the work. Let me know if anyone is willing.

**Comment by m-parashar** [comment]
https://github.com/m-parashar/emax64/releases/tag/20191225

See if this release helps.

**Comment by xeijin** [comment]
@m-parashar I can see some icons now in the mode-line (e.g. the icon for git) but I get the feeling these are glyphs from fonts rather than images, the mode-line looks a little strange, very much like the one from terminal rather than GUI emacs

**Comment by etern** [comment]
The problem still exists in latest release [emax64-28.0.50-20191229](https://github.com/m-parashar/emax64/releases/tag/20191229), cannot use nyan-mode, since nyan-mode uses XPM, I tested with `(image-type-available-p 'xpm)`, it returns `nil`.

I'm currently using this release [pdumper-20180619](https://github.com/m-parashar/emax64/releases/tag/pdumper-20180619), `(image-type-available-p 'xpm)` returns `t`

**Comment by etern** [comment]
Copy the `libXpm-noX4.dll` from [pdumper-20180619](https://github.com/m-parashar/emax64/releases/tag/pdumper-20180619)/bin to [emax64-28.0.50-20191229](https://github.com/m-parashar/emax64/releases/tag/20191229)/bin can solve the problem.

[Here the doc](https://www.gnu.org/software/emacs/manual/html_node/elisp/Dynamic-Libraries.html#Dynamic-Libraries) says xpm need libxpm

**Comment by m-parashar** [comment]
The latest release should have solved this. Please reopen if it hasn't.
