### ISSUE TITLE
ImageMagick a mixed blessing

### ISSUE THREAD

**Issue by c256** [m-parashar/emax64#28]
Have you tried abandoning ImageMagic support for the native image transformation code added recently? IM itself seems to be the bug/exploit that keeps on giving, which makes it rough to use for things found in email and web pages.

**Comment by m-parashar** [comment]
I uploaded an unpatched build of 26.3 and emacs-master a couple days ago. Native image transformation is nice but lacks even basic features like fine rotation, especially on Windows. I will release unpatched/vanilla builds of 27.x and emacs-master along with IM7 builds since IM doesn't play nice with pdf-tools either, so that should cover both bases.

**Comment by c256** [comment]
Gotcha. I believe that those features were added to emacs native image transformation code, even on Windows, but after the 26.3 release, based on this thread on emacs-devel: https://lists.gnu.org/archive/html/emacs-devel/2019-06/msg00242.html
Are you saying that you not seeing sufficient support from master? Perhaps I'm confused about how that turned out in the end.  Thanks!
